### ISSUE TITLE
question about classifiers implementation

### ISSUE THREAD

**Issue by DRJYYDS** [GuoQiushan/EGC#1]
Nice to see this impressive work. How do you guys implement the classifier using the U-net arch? (And when will you release the code?

**Comment by GuoQiushan** [comment]
Hi, Thanks for your interest in our work. As described in Sec.4.1, we attach an attention pooling module on the top of UNet. The code will be released soon after I clean the code and reproduce the results.

**Comment by DRJYYDS** [comment]
> Hi, Thanks for your interest in our work. As described in Sec.4.1, we attach an attention pooling module on the top of UNet. The code will be released soon after I clean the code and reproduce the results.

Get it, nice idea to apply Unet as the backbone, I may also wanna know how does the GPU memory cost compared to wider-Resnt and UNET as gradient direct?
