### ISSUE TITLE
Some questions about future work.

### ISSUE THREAD

**Issue by ddghjikle** [GuoQiushan/EGC#2]
As EGC combines classification and generation into the forward and backward processes, this work provides us a new kind of invertible neural networks. I am curious whether the classification task can be replaced by other tasks such as image caption or question answering. By the way, I hope the codes can be released as soon as possible. Thanks for sharing.

**Comment by GuoQiushan** [comment]
Thanks for your interest in our work. That's a very good point, and we are currently working on expanding EGC to other tasks, such as image captioning.
