### ISSUE TITLE
Do we need to compute second order derivative during training?

### ISSUE THREAD

**Issue by huanranchen** [GuoQiushan/EGC#3]
Hi~ 
I have a question about training procedure. Do we need to compute second order derivative during training, for this:

![image](https://user-images.githubusercontent.com/28839782/232288176-5d253df4-bdd3-4d67-85f1-1eb085b6bebf.png)

**Comment by GuoQiushan** [comment]
Hi huanran,

The second-order mixed partial derivative is required to optimize the parameters \theta. You may use the torch.autograd.grad function to implement the loss.

**Comment by huanranchen** [comment]
Thank you~
